apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-yaml
    method: fromcode
    onemore: lable
  name: nginx-yaml
spec:
  containers:
  - image: nginx
    name: nginx-yaml
    resources: {}
